baseURL = 'https://yourusername.github.io/olk-hidku-post-app/'
languageCode = 'es'
title = 'Hidku'

[params]
  description = "Sitio web personal de Hidku - Desarrollador y creador de contenido"
  author = "Hidku"

# Men√∫ personalizado manejado en el template baseof.html